version: '3'
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    networks:
      - infra
    ports:
      - "8848:8848"
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    labels:
      NAME: "nacos"
  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - infra
    ports:
      - "3306:3306"
    restart: always
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=beego
    volumes:
      - "${DOCKER_VOL_DIR}/mysql/data:/var/lib/mysql"
      - "${DOCKER_VOL_DIR}/mysql/conf:/etc/mysql/conf.d"
      - "${DOCKER_VOL_DIR}/mysql/logs:/logs"
    labels:
      NAME: "mysql"
  redis:
    image: redis:3.2
    container_name: redis
    networks:
      - infra
    ports:
      - "6379:6379"
    volumes:
      - "${DOCKER_VOL_DIR}/redis/conf:/usr/local/etc/redis"
      - "${DOCKER_VOL_DIR}/redis/data:/data"
    command: redis-server --requirepass 123456
    environment:
      - TZ=Asia/Shanghai
    labels:
      NAME: "redis"
  rabbitmq:
    image: "rabbitmq:3.7-management"
    container_name: rabbitmq
    networks:
      - infra
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    hostname: "rabbitmq"
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - "${DOCKER_VOL_DIR}/rabbitmq/lib:/var/rabbitmq/lib"
    labels:
      NAME: "rabbitmq"
  hippo:
    image: cloud/cloud-hippo:1.1.0-SNAPSHOT
    container_name: hippo
    networks:
      - infra
      - cloud
    ports:
      - "8223:8223"
    environment:
      - NACOS_HOST=nacos
      - DB_HOST=mysql
      - DB_SCHEMA=cloud
      - REDIS_HOST=redis
      - REDIS_DB=0
      - RABBITMQ_HOST=rabbitmq
      - spring.profiles.active=docker
    volumes:
      - "${DOCKER_VOL_DIR}/cloud-hippo/logs:/logs/cloud-hippo"
    depends_on:
      - nacos
      - mysql
      - redis
      - rabbitmq
  #    links:
  #      - nacos
  #      - mysql
  #      - redis
  #      - rabbitmq
  owl:
    image: cloud/cloud-owl:1.1.0-SNAPSHOT
    container_name: owl
    networks:
      - infra
      - cloud
    ports:
      - "7211:7211"
    environment:
      - NACOS_HOST=nacos
      - DB_HOST=mysql
      - DB_SCHEMA=cloud
      - REDIS_HOST=redis
      - REDIS_DB=0
      - RABBITMQ_HOST=rabbitmq
      - spring.profiles.active=docker
    volumes:
      - "${DOCKER_VOL_DIR}/cloud-owl/logs:/logs/cloud-owl"
    depends_on:
      - nacos
      - mysql
      - redis
      - rabbitmq
      - hippo
  #    links:
  #      - nacos
  #      - mysql
  #      - redis
  #      - rabbitmq
  spider:
    image: cloud/cloud-spider:1.1.0-SNAPSHOT
    container_name: spider
    networks:
      - infra
      - cloud
    ports:
      - "8888:8888"
    environment:
      - NACOS_HOST=nacos
      - DB_HOST=mysql
      - DB_SCHEMA=cloud
      - REDIS_HOST=redis
      - REDIS_DB=0
      - RABBITMQ_HOST=rabbitmq
      - spring.profiles.active=docker
    volumes:
      - "${DOCKER_VOL_DIR}/cloud-spider/logs:/logs/cloud-spider"
    depends_on:
      - nacos
      - mysql
      - redis
      - rabbitmq
      - hippo
      - owl
#    links:
#      - nacos
#      - mysql
#      - redis
#      - rabbitmq

networks:
  #基础设施层网络
  infra:
  #平台服务层网络
  cloud: