version: '3'
services:
  spider:
    image: registry.cn-hangzhou.aliyuncs.com/smart4y/cloud-spider:1.0.0
    container_name: spider
    networks:
      - infra
      - cloud
    ports:
      - "8888:8888"
    environment:
      - NACOS_HOST=nacos
      - DB_HOST=mysql
      - DB_SCHEMA=cloud
      - REDIS_HOST=redis
      - REDIS_DB=0
      - RABBITMQ_HOST=rabbitmq
      - spring.profiles.active=docker
    volumes:
      - "${DOCKER_VOL_DIR}/cloud-spider/logs:/logs/cloud-spider"
    entrypoint: "/wait-for-it.sh -t 0 owl:7211 --"
    command:
      - /bin/sh
      - -c
      - java -DXms256m -DXmx768m -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    healthcheck:
      test: "/bin/netstat -anp | grep 8888 && exit 0 || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
networks:
  #基础设施层网络
  infra:
  #平台服务层网络
  cloud: