version: '3'
services:
  nacos:
    image: nacos/nacos-server:1.1.3
    container_name: nacos
    networks:
      - infra
    ports:
      - "8848:8848"
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    healthcheck:
      test: "curl localhost:8848/nacos/actuator/health && exit 0 || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
    labels:
      NAME: "nacos"
  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - infra
    ports:
      - "13306:3306"
    restart: always
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - "${DOCKER_VOL_DIR}/mysql/data:/var/lib/mysql"
      - "${DOCKER_VOL_DIR}/mysql/conf:/etc/mysql/conf.d"
      - "${DOCKER_VOL_DIR}/mysql/logs:/logs"
    healthcheck:
      test: "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD && test '0' -eq $$(ps aux | awk '{print $$11}' | grep -c -e '^mysql$$')"
      interval: 15s
      timeout: 5s
      retries: 128
    labels:
      NAME: "mysql"
  nginx:
    image: "nginx:1.17.5"
    container_name: nginx
    networks:
      - infra
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DOCKER_VOL_DIR}/nginx/conf.d:/etc/nginx/conf.d"
      - "${DOCKER_VOL_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "${DOCKER_VOL_DIR}/nginx/cert:/etc/nginx/cert"
      - "${DOCKER_VOL_DIR}/nginx/html:/usr/share/nginx/html"
      - "${DOCKER_VOL_DIR}/nginx/admin:/usr/share/nginx/admin"
      - "${DOCKER_VOL_DIR}/nginx/logs:/var/log/nginx"
    healthcheck:
      test: "service nginx status || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
    labels:
      NAME: "nginx"
  rabbitmq:
    image: "rabbitmq:3.7-management"
    container_name: rabbitmq
    networks:
      - infra
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    hostname: "rabbitmq"
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - "${DOCKER_VOL_DIR}/rabbitmq/lib:/var/rabbitmq/lib"
    healthcheck:
      test: "rabbitmqctl eval '{ true, rabbit_app_booted_and_running } = { rabbit:is_booted(node()), rabbit_app_booted_and_running }, { [], no_alarms } = { rabbit:alarms(), no_alarms }, [] /= rabbit_networking:active_listeners(), rabbitmq_node_is_healthy. ' || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
    labels:
      NAME: "rabbitmq"
  redis:
    image: redis:3.2
    container_name: redis
    networks:
      - infra
    ports:
      - "16379:6379"
    volumes:
      - "${DOCKER_VOL_DIR}/redis/conf:/usr/local/etc/redis"
      - "${DOCKER_VOL_DIR}/redis/data:/data"
    command: redis-server --requirepass 123456
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: "redis-cli -h 127.0.0.1 ping && exit 0 || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
    labels:
      NAME: "redis"
  hippo:
    image: registry.cn-hangzhou.aliyuncs.com/smart4y/cloud-hippo:1.0.0
    container_name: hippo
    networks:
      - infra
      - cloud
    ports:
      - "8223:8223"
    environment:
      - NACOS_HOST=nacos
      - DB_HOST=mysql
      - DB_SCHEMA=cloud
      - REDIS_HOST=redis
      - REDIS_DB=0
      - RABBITMQ_HOST=rabbitmq
      - spring.profiles.active=docker
    volumes:
      - "${DOCKER_VOL_DIR}/cloud-hippo/logs:/logs/cloud-hippo"
    depends_on:
      - nginx
      - nacos
      - mysql
      - redis
      - rabbitmq
    entrypoint: "/wait-for-it.sh -t 0 nacos:8848 --"
    command:
      - /bin/sh
      - -c
      - java -DXms256m -DXmx768m -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    healthcheck:
      test: "/bin/netstat -anp | grep 8223 && exit 0 || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
  owl:
    image: registry.cn-hangzhou.aliyuncs.com/smart4y/cloud-owl:1.0.0
    container_name: owl
    networks:
      - infra
      - cloud
    ports:
      - "7211:7211"
    environment:
      - NACOS_HOST=nacos
      - DB_HOST=mysql
      - DB_SCHEMA=cloud
      - REDIS_HOST=redis
      - REDIS_DB=0
      - RABBITMQ_HOST=rabbitmq
      - spring.profiles.active=docker
    volumes:
      - "${DOCKER_VOL_DIR}/cloud-owl/logs:/logs/cloud-owl"
    depends_on:
      - hippo
    entrypoint: "/wait-for-it.sh -t 0 hippo:8223 --"
    command:
      - /bin/sh
      - -c
      - java -DXms256m -DXmx512m -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    healthcheck:
      test: "/bin/netstat -anp | grep 7211 && exit 0 || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
  spider:
    image: registry.cn-hangzhou.aliyuncs.com/smart4y/cloud-spider:1.0.0
    container_name: spider
    networks:
      - infra
      - cloud
    ports:
      - "8888:8888"
    environment:
      - NACOS_HOST=nacos
      - DB_HOST=mysql
      - DB_SCHEMA=cloud
      - REDIS_HOST=redis
      - REDIS_DB=0
      - RABBITMQ_HOST=rabbitmq
      - spring.profiles.active=docker
    volumes:
      - "${DOCKER_VOL_DIR}/cloud-spider/logs:/logs/cloud-spider"
    depends_on:
      - owl
    entrypoint: "/wait-for-it.sh -t 0 owl:7211 --"
    command:
      - /bin/sh
      - -c
      - java -DXms256m -DXmx768m -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    healthcheck:
      test: "/bin/netstat -anp | grep 8888 && exit 0 || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
networks:
  #基础设施层网络
  infra:
  #平台服务层网络
  cloud: