version: '3'
services:
  hippo:
    image: cloud/cloud-hippo:1.1.0-SNAPSHOT
    container_name: hippo
    networks:
      - infra
      - cloud
    ports:
      - "8223:8223"
    environment:
      - NACOS_HOST=nacos
      - DB_HOST=mysql
      - DB_SCHEMA=cloud
      - REDIS_HOST=redis
      - REDIS_DB=0
      - RABBITMQ_HOST=rabbitmq
      - spring.profiles.active=docker
    volumes:
      - "${DOCKER_VOL_DIR}/cloud-hippo/logs:/logs/cloud-hippo"
    depends_on:
      - nacos
      - mysql
      - redis
      - rabbitmq
    entrypoint: "/wait-for-it.sh -t 0 nacos:8848 --"
    command:
      - /bin/sh
      - -c
      - java -DXms256m -DXmx768m -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    healthcheck:
      test: "/bin/netstat -anp | grep 8223 && exit 0 || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
networks:
  #基础设施层网络
  infra:
  #平台服务层网络
  cloud: