version: '3'
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    networks:
      - infra
    ports:
      - "8848:8848"
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    healthcheck:
      test: "/bin/netstat -anp | grep 8848 && exit 0 || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
    labels:
      NAME: "nacos"
  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - infra
    ports:
      - "3306:3306"
    restart: always
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=beego
    volumes:
      - "${DOCKER_VOL_DIR}/mysql/data:/var/lib/mysql"
      - "${DOCKER_VOL_DIR}/mysql/conf:/etc/mysql/conf.d"
      - "${DOCKER_VOL_DIR}/mysql/logs:/logs"
    healthcheck:
      test: "/bin/netstat -anp | grep 3306 && exit 0 || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
    labels:
      NAME: "mysql"
  nginx:
    image: "nginx:1.17.5"
    container_name: nginx
    networks:
      - infra
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: "/bin/netstat -anp | grep 80 && exit 0 || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
    labels:
      NAME: "nginx"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DOCKER_VOL_DIR}/nginx/conf.d:/etc/nginx/conf.d"
      - "${DOCKER_VOL_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "${DOCKER_VOL_DIR}/nginx/cert:/etc/nginx/cert"
      - "${DOCKER_VOL_DIR}/nginx/html:/usr/share/nginx/html"
      - "${DOCKER_VOL_DIR}/nginx/admin:/usr/share/nginx/admin"
      - "${DOCKER_VOL_DIR}/nginx/logs:/var/log/nginx"
  rabbitmq:
    image: "rabbitmq:3.7-management"
    container_name: rabbitmq
    networks:
      - infra
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    hostname: "rabbitmq"
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - "${DOCKER_VOL_DIR}/rabbitmq/lib:/var/rabbitmq/lib"
    healthcheck:
      test: "/bin/netstat -anp | grep 5672 && exit 0 || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
    labels:
      NAME: "rabbitmq"
  redis:
    image: redis:3.2
    container_name: redis
    networks:
      - infra
    ports:
      - "6379:6379"
    volumes:
      - "${DOCKER_VOL_DIR}/redis/conf:/usr/local/etc/redis"
      - "${DOCKER_VOL_DIR}/redis/data:/data"
    command: redis-server --requirepass 123456
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: "/bin/netstat -anp | grep 6379 && exit 0 || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
    labels:
      NAME: "redis"

networks:
  #基础设施层网络
  infra:
  #平台服务层网络
  cloud: