version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3.7-management"
    container_name: rabbitmq
    networks:
      - infra
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    hostname: "rabbitmq"
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - "${DOCKER_VOL_DIR}/rabbitmq/lib:/var/rabbitmq/lib"
    healthcheck:
      test: "rabbitmqctl eval '{ true, rabbit_app_booted_and_running } = { rabbit:is_booted(node()), rabbit_app_booted_and_running }, { [], no_alarms } = { rabbit:alarms(), no_alarms }, [] /= rabbit_networking:active_listeners(), rabbitmq_node_is_healthy. ' || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
    labels:
      NAME: "rabbitmq"
networks:
  #基础设施层网络
  infra: