version: '3'
services:
  redis:
    image: redis:3.2
    container_name: redis
    networks:
      - infra
    ports:
      - "6379:6379"
    volumes:
      - "${DOCKER_VOL_DIR}/redis/conf:/usr/local/etc/redis"
      - "${DOCKER_VOL_DIR}/redis/data:/data"
    command: redis-server --requirepass 123456
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: "/bin/netstat -anp | grep 6379 && exit 0 || exit 1"
      interval: 15s
      timeout: 5s
      retries: 128
    labels:
      NAME: "redis"
networks:
  #基础设施层网络
  infra: